### PR TITLE
document allowedOrigins values in README

### LINKED ISSUE #41: allowedOrigins spec
It's very unclear what the spec is for the allowedOrigins setting. Given some diggign in the code, I'm pretty sure it's what's here: http://download.eclipse.org/jetty/stable-9/apidocs/org/eclipse/jetty/servlets/CrossOriginFilter.html. But it appears that if there's a \* you are validating as a regex, which is not correct according to the above documentation.

### PR DESCRIPTION
**Pull request by jmcampanini**
fixes #41 

related to #42 since it mentions that the values are passed through as `init` params.

### CODE REVIEW

**Comment by qinfchen** [comment]
:+1:

**Comment by jmcampanini** [comment]
// tagging @bschimpf since it was his original issue, waiting for his +1

**Comment by bschimpf** [comment]
Hey, I'm pretty sure this is incorrect -- it's not truly a regex, it's a regex except that "." is replaced with "." and "_" is replaced with "._" (so that *.example.com works as expected).

**Comment by jmcampanini** [comment]
+1 will be fixing this

**Comment by tomshen** [comment]
@jmcampanini can you fix this or close?

**Pull request closed without merging**
