### PR TITLE
Update web-security-bundle for dropwizard 1.0.0

### PR DESCRIPTION
**Pull request by carterkozak**
This version, like dropwizard 1.0.0, supports java 8+

### CODE REVIEW

**Comment by carterkozak** [comment]
@jmcampanini 
@qinfchen

**Comment by carterkozak** [comment]
~~This appears to be a build flake, passes locally.
I don't seem to have perms to retrtigger.~~ regenerated the commit to force a build

**Comment by jmcampanini** [comment]
we haven't switched over to 1.0 yet, but i'm glad it seems that the changes are minimal for this bundle.

when we switch over to 1.0, it would make sense to pull this bundle along. i don't know of a timeframe atm, tagging @zoubeiri for input on timelines

**Comment by carterkozak** [comment]
This blocks other apps from moving to 1.0.0, not the inverse.
I would like to use this with an app that is based on dropwizard 1, and forking doesn't seem like the correct approach.

**Comment by jmcampanini** [comment]
tagging @mnazbro since he's going to contribute code to publish 2 artifacts

**Comment by jmcampanini** [comment]
relevant PR to DW 1.0: https://github.com/dropwizard/dropwizard/commit/c436e5e28406ece6ae1250be3268a638ed90bc5b

**Comment by qinfchen** [comment]
@cakofony, can you elaborate on why the current version can't be used for dropwizard 1.0 apps?

**Comment by mnazbro** [comment]
@qinfchen The return type from `getJerseyRootPath` has changed from `String` to `Optional<String>`

**Comment by qinfchen** [comment]
Is it worth the effort to fix that instead of bumping the version of DW first? Bumping the DW version to 1.0 means pre 1.0 apps won't be able to use new verison

**Comment by carterkozak** [comment]
> Bumping the DW version to 1.0 means pre 1.0 apps won't be able to use new verison

That is correct, they can use existing versions. If we find flaws with them, we can build patch releases to fix them.

Attempting to support unsupported dw versions feels like a recipe for unmaintainable code.

**Comment by jmcampanini** [comment]
> Attempting to support unsupported dw versions feels like a recipe for unmaintainable code.

+1. but it seems we may need to support jdk7 - hence 0.9.x for a bit longer. we should catch up on Monday (highline + @mnazbro + @cakofony)

**Comment by qinfchen** [comment]
Most of the apps are using 0.9.x at the moments and it would take a while for us to move 1.0. I wouldn't say 0.9.x versions are unsupported :)

**Comment by gracew** [comment]
there's been no development on this project since May 9, why can't we upgrade to dropwizard 1.0?  If anything we should be pushing apps to upgrade their dependency as well.

**Comment by gracew** [comment]
I generally think we need to be upgrading aggressively vs taking a "lowest common denominator" approach

**Comment by mnazbro** [comment]
@gracew There is currently development on a plan in place to upgrade to Dropwizard 1.0. We must maintain both versions because there are services that _cannot_ upgrade to Java 8. While we do want to push for the future, there are external constraints to consider.

I'd argue that having a support branch for an 0.9 version of dropwizard versus having two versions of the bundle in master are implementation details which will be decided when the plan is finalized.

**Comment by qinfchen** [comment]
@gracew shared the doc with you. As @mnazbro pointed out, there are multiple breaking changes in 1.0 and we need to have a plan to update the bundles and migrate the projects over to 1.0

**Comment by qinfchen** [comment]
👍 LGTM, @cakofony can you rebase the changes?

**Pull request merged**
