### PR TITLE
use compileOnly for annotations required at compile time

### PR DESCRIPTION
**Pull request by qinfchen**
cleaner fix for https://github.com/palantir/dropwizard-web-security/issues/54

### CODE REVIEW

**Comment by jmcampanini** [comment]
why did this get closed?

**Comment by qinfchen** [comment]
doesn't work properly :( unfortunately. It seems like a bug in immutables

**Comment by qinfchen** [comment]
Don't delete the branch yet :)

**Comment by jmcampanini** [comment]
np. just was curious, since there were no comments

**Pull request closed without merging**
