### PR TITLE
Feature/no optional config

### PR DESCRIPTION
**Pull request by jmcampanini**

### CODE REVIEW

**Comment by jmcampanini** [comment]
fixes #18 

this is an back-compt break, since we change the interface to require the presence of a `WebSecurityConfiguration`. the example code is linked that has a `DEFAULT` impl ready to use.

this all came up when @rcchen had to mix in java8 vs guava `Optional`.

this change doesn't impose how they parse their YAML file, just how the configuration class is defined.

// tagging for SA @bavardage @leeavital

**Comment by jmcampanini** [comment]
on second thought, this doesn't make it clear that the default values can/should be used and you can basically omit the `webSecurity` YAML block in most cases. unless we provide clearer examples for modifying your `Configuration` object...

@rcchen how horrible is it to stay with guava's `Optional` until DW switches to java8 - making this issue go away?

**Comment by rcchen** [comment]
I don't have super strong feelings about it. I don't like how it looks in the code, but I don't think it's a deal-breaker for now (cc: @jlz27 for commentary).

**Comment by jmcampanini** [comment]
going to close this. i feel that having an `Optional` there encourages the defaults to be used.

**Pull request closed without merging**
